a = Analysis(
    [
        "backend/main.py",
        "backend/api.py",
        "backend/backend_api.py",
        "backend/test_api.py",
        "backend/test_backend_api.py",
        "backend/test_refresh_scenario.py",
    ],
    pathex=["backend"],
    binaries=[],
    datas=[(".\\frontend\\dist", "frontend/dist")],
    hiddenimports=["appdirs"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="HoHatch",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=".\\\\frontend\\\\public\\\\favicons\\\\favicon.ico",
)