a = Analysis(
    [
        "../main.py",
        "../api.py",
        "../backend_api.py",
        "../dto.py",
        "../exceptions.py",
        "../services.py",
        "../version.py",
    ],
    binaries=[],
    datas=[("..\\..\\frontend\\dist", "frontend/dist")],
    hiddenimports=["appdirs"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="HoHatch",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # build
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='../version.rc',
    icon="../../frontend/public/favicons/favicon.ico",
)
