a = Analysis(
    [
        "../src/main.py",
        "../src/api.py",
        "../src/backend_api.py",
        "../src/test_api.py",
        "../src/test_backend_api.py",
        "../src/test_refresh_scenario.py",
    ],
    pathex=["../src"],
    binaries=[],
    datas=[("..\\..\\frontend\\dist", "frontend/dist")],
    hiddenimports=["appdirs"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="HoHatch",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # build
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="../../frontend/public/favicons/favicon.ico",
)
