name: Release Application

on:
  workflow_run:
    workflows: ["Preflight Check"]
    branches: [master]
    types:
      - completed

jobs:
  build-and-release:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0 # Fetch all history for git tag checks

      - name: Fetch all tags
        run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\pip install -r requirements.txt

      - name: Install Node.js dependencies
        working-directory: .\frontend
        run: npm install

      - name: Build frontend
        working-directory: .\frontend
        run: npm run frontend

      - name: Build executable
        working-directory: .\frontend
        run: npm run backend:windows
        shell: cmd

      - name: List dist directory
        run: ls dist

      - name: Get package version
        id: get_version
        run: |
          $packageVersion = (node -p "require('./frontend/package.json').version")
          "PACKAGE_VERSION=$packageVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Check if tag already exists
        id: check_tag
        run: |
          $TAG_NAME = "v${{ env.PACKAGE_VERSION }}"
          if ((git tag -l $TAG_NAME | Select-String -Pattern $TAG_NAME) -ne $null) {
            Write-Host "Tag $TAG_NAME already exists. Skipping release."
            "tag_exists=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            Write-Host "Tag $TAG_NAME does not exist. Proceeding with release."
            "tag_exists=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

      - name: Create README for release
        run: |
          mkdir release_package
          $readmeContent = "HoHatch - JPG/DDS Image Converter for Shadowverse: Worlds Beyond`r`n`r`nThank you for downloading HoHatch!`r`n`r`nRun HoHatch.exe to start the application.`r`n`r`nFor more information, please visit the official website:`r`nhttps://hohatch.draco.moe"
          Set-Content -Path "release_package/README.txt" -Value $readmeContent
        shell: powershell

      - name: Prepare files for packaging
        run: Copy-Item -Path "dist/HoHatch.exe" -Destination "release_package/"
        shell: powershell

      - name: Create ZIP archive
        id: archive
        run: |
          $ARCHIVE_NAME = "HoHatch-v${{ env.PACKAGE_VERSION }}.zip"
          Compress-Archive -Path "release_package/*" -DestinationPath $ARCHIVE_NAME
          "ARCHIVE_NAME=$ARCHIVE_NAME" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        shell: powershell

      - name: Create Release
        id: create_release
        if: ${{ steps.check_tag.outputs.tag_exists == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: Release v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: ${{ steps.check_tag.outputs.tag_exists == 'false' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.archive.outputs.ARCHIVE_NAME }}
          asset_name: ${{ steps.archive.outputs.ARCHIVE_NAME }}
          asset_content_type: application/zip
